<?php

  echo ("
  <h2>Roads & Driving</h2>
  <p class='justif'>
  Although roads between Costa Rica’s most popular destinations are mostly paved reaching more off-the-beaten path locations will definitely require driving on gravel or dirt roads. Although road conditions are overall quite good, expect to find large deep potholes on some of the roads.  Also, road conditions can change quickly in Costa Rica due to weather, natural disasters, construction, and other factors. For instance, during the rainy season, flash floods have been known to deteriorate and even wash out roads and bridges. If planning to visit or drive through San Jose city, you need to avoid rush hours when traffic can often be heavy and you need to be aware that the driving ‘etiquette’ will be quite different to that of the U.S.A. or Europe.<br/><br/>
  Estimating driving times between locations by merely studying map routes can be quite misleading as unlike European and U.S.A. roads where engineered and constructed following direct routes between destinations. However, most of Costa Rica’s road network has been a natural evolution from mule and horse trails dating back colonical times which then became oxcart routes and finally became dirt roads which over the last few decades just got paved! So, this means that routes between many cities and towns follow long winding routes around mountains which result in longer driving times but yet very scenic routes with spectacular views and landscapes.<br/><br/>
  Road signs in Costa Rica are basically non-existent which will result in requiring some good route finding skills in order to figure out where you are on any map regardless of how detail it may be as many of the roads in Costa Rica may be numbered on a map, but they are not marked with any actual road signs! Using a GPS or the popular Waze App is recommended in order to make sure you are on the right road at all times! A map is still a great alternative resource specially if you are visiting rural areas where there may not be internet signal.
  </p>");
?>
