<h3 style="margin-top: 0px">I.BOOKING &amp; RESERVATION POLICIES</h3>
<h3>1. Itinerary Proposals</h3>
<ol class="tcList3">
    <li>Costa Rica Reps will design custom itineraries based on travellers' special requests according to their interests, ages, physical conditions, season, length of stay, preferred accommodation, transportation and logistics. Once the final itinerary and quote are confirmed, Costa Rica Reps will be in charge of making all due reservations. Whilst Costa Rica Reps will do its utmost to abide to the original travel plans, it estates that that based on services availability at the time of booking them may result in modifications such as changes in locations visited, hotels used and the sequence of the itinerary itself.</li>
    <li>Given the popularity of Costa Rica as a destination and high service demand, it is escential to make bookings well in advance in order to guarantee your preferred hotel choices and services. We recommend making booking at least 6 months in advance during the High Season which includes Nov 15 to April 16 and July 1 to August 30th. For bookings during the Peak Season (Dec 20 to Jan 5th) and Easter we strongly recommend making reservations at least 1 year in advance in order to ensure you get space. Alternatively, Costa Rica Reps offers a variety of soft-adventure, family travel and nature oriented itineraries throughout the year based on a minimum of 2 travellers. Please enquire if your request is for a solo traveler as we advise of currently confirmed tours or customize a package taking into consideration existing confirmed services in order to prove the most competitive quote.</li>
    <li>Quoted prices are quoted in U.S. Dollars and are valid at the time of making the proposal. We recommend confirming your quote and travel plans within 3 days after the final proposal is sent. Should a price change occur or increase, it will be notified to the booking agent as it becomes of our knowledge or at the time of reviewing a modified quote request. Any ammendments will be made to a quote as necessary. Everytime the quote is modified or services are changed by you as it becomes a new quote.</li>
    <li>All quotes have a validity of a maximum of a week (7 days) and are subject to changes depending on the availability of services. Quotes are subject to changes and price revision when:
        <ul>
            <li>The confirmation for the quote is received after 7 days of having sent the quote.</li>
            <li>Services are not available as quoted.</li>
            <li>There are changes out of our control or which could have not been foreseen at the time of quoting based on the information received or the existing conditions. In order to reduce the risk of unfoseen costs, it is very useful for us to receive alomg with your reservation as much information about the clients, their expectation, special requirements, medical conditions, etc.</li>
        </ul></li>
    <li>In order to ensure we get the rooms at your preferred hotel choices, it is strongly recommended that a request is made in order to block the rooms when clients are seriously interested in booking.</li>
</ol>