<style>
    * {text-align: justify; padding-right: 5px;}
    li {font: 16px Candara;}

</style>


<ol style="list-style-type: lower-alpha;">
    
    <li>The contents of this website are subject to change without prior notice. Information on the C.R. Reps&trade; website is provided by many different sources, including our staff members, providers, trade partners and government institutions. Whilst our goal is to ensure the content accuracy and every effort is made in maintaining an up-to-date presence, C.R. Reps&trade; cannot guarantee that it always will be. The information provided may contained errors and omissions and may not be valid (including published prices) at the time of accessing the website.
    No warranties, promises or representations of any kind, express or implied, are given as to the accuracy of any of the information on this Site or as to the nature, standard, suitability or otherwise of any services offered by us or on our behalf. We shall not be liable for any loss or damage of whatever nature (direct, indirect, consequential or other) that may arise as a result, directly or indirectly, from the use of any of the information or material contained on this Site and/or the use of or access to any other information or material via web links from this Site,  any service interruption, inability to access this site or to complete any transaction. C.R. Reps&trade;  does not warrant that this Site is free from computer viruses or other properties that may cause loss or damage.
    Should you see something on the C.R. Reps&trade; website that should be corrected or updated, please send an email to the Information Technology Services Division at admin@costaricareps.com. Be sure to reference the full URL of the page in your correspondence so we can quickly locate the information in question.  The C.R. Reps&trade; website is designed, updated and technologically supported by our own Information Technology Services Division.</li>
    <br><li><b>Access to the Services</b><br>
    You are responsible for making all arrangements necessary for you to have access to the Services, including and without limitation, providing suitable computer hardware and access to the Internet. C.R. Reps&trade; Reserves the right in its absolute discretion on any ground it sees fit not to accept your order or to terminate an existing order, and is under no obligation to explain its decision.
    Minimum technical requirements:
    The minimum browser requirements to use all Costa Rica Reps&trade; functions are: Microsoft Internet Explorer 7 and higher, Mozilla Firefox 3.x and higher, Apple Safari 4.x and higher, Google Chrome 4.x and higher. Unfortunately, Costa Rica Reps&trade; system is no longer compatible with older software versions.</li>
    <br><li><b>Photographic & Video Content:</b><br>
    Whilst C.R. Reps&trade; endeavours to  maintain the photographic material and video footage which appears on this website as up-to-date as possible, we accept no liability for any changes which may occur between the time the photographs were taken or the filming  was done, and the time you come to view the photographs, the footage or use the service. The images and other information contained on this Site do not form part of any holiday contract which you may subsequently enter into. There is no guarantee given that any of the facilities , amenities or services featured in the photographs or video footage will be available when the services are actually provided or at the time of  travel. Certain free services, facilities, and extra amenities such as additional tours, air conditioning, etc. that are featured on this website may be withdrawn at any time or may only be provided if you pay an additional charge. We sprongly advise you that any specific services, facilities and amenities are verified and you ask them be conformed in writing at time of booking.</li>
    <br><li><b>Links to Other Internet Sites</b><br>
    The Website may contain links to other Internet websites and services that are operated, and maintained by third parties. You acknowledge, understand and agree that Costa Rica Reps&trade;  will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, products or services available on such other websites.</li>
    <br><li><b>Personal Information</b><br>
    C.R. Reps&trade; seeks to protect the privacy and information of all those who use our Service. We will collect and processes personal information that you provide to us when signing up for our Services. This data includes: Your email address, content, and any other information provided by you. If you contact C.R. Reps&trade;, we may keep a record of that correspondence.
    C.R. Reps&trade; may collect information about your computer, including where available your IP address, operating system and browser type, for the purposes of system administration and to report aggregate information to its advertisers or other third parties
    C.R. Reps&trade; may disclose personal information and other information about you where C.R. Reps&trade; is under a duty to disclose or share your personal data in order to comply with any valid legal process, such as search warrants and court orders, or other valid law enforcement obligations, or to protect itself or others, or establish or exercise its legal rights or defend against legal claims.</li>
    <br><li><b>Proprietary Rights in Website Content</b><br>
    Costa Rica Reps&trade; is the owner or the licensee of all intellectual property rights in the Website and all information, content, text, graphics, design, compilation, selection and arrangement of elements, organization, software, and other content that make up the Website and/or the Service (the "Content"). You acknowledge that certain Content available on the Website is protected by copyright laws and treaties around the world, and trademark, patent or other intellectual property rights of C.R. Reps&trade; or its licensors. Except as expressly provided herein, nothing within the Website or Service shall be construed as conferring any right or license under any of C.R. Reps&trade; intellectual property rights, whether by estoppel, implication, waiver or otherwise.
    Except as otherwise provided herein, you agree that you will not transmit, distribute, sell, reproduce, alter, reverse engineer, modify, create derivative works, broadcast or publicly display any Content from the Website without the prior express written permission of C.R. Reps&trade; for whatever propose personal or commercial.
    All trademarks, service marks, and trade names appearing on the Website are the property of Costa Rica Reps&trade; or the respective owners of such marks or names, and are protected by Costa Rican, U.S. and international copyright and trademark laws. You agree not to defame or disparage C.R. Reps&trade; and its trademarks, service marks, and trade names, or any other aspect of the Website or the Content. Any use of the trademarks, service marks, or trade names appearing throughout the Website without the express written consent of C.R. Reps&trade; or the owner of the mark or name, as applicable, is strictly prohibited. All rights not expressly granted in these Terms of Use are reserved.</li>
    <br><li><b>Limitation of Liability></b><br>
    To the maximum extent permitted by applicable Law, in no event will Costa Rica Reps&trade;, its employees, suppliers, agents or licensors be liable for any indirect, special consequential, incidental; Or punitive damages; Lost profits, revenue, interest or business; Whether foreseeable or unforeseeable, rising out of or related to your or any third party's claim (including, but not limited to, reliance on or the use of , delay in being able to use, or inability to use, the services, the website, the content it provides, or any hyper-linked website or any third party products or services) regardless of legal theory, even if Costa Rica Reps&trade; has been advised of the possibility of such damages.  In no event will the aggregate liability incurred for all damages, losses and causes of action exceed the amount actually paid for the services at issue. This Liability cap will not apply only when to the extent that applicable law requires liability despite the exclusions and limitations set forth above.</li>
    <br><li><b>Indemnity</b><br>
    You agree to indemnify and hold harmless Costa Rica Reps&trade;, its employees, suppliers, agents and licensors from any third-party claim, liability, loss, damage, cost or expense (including without limitation reasonable attorney’s fees) arising out of or related to access and use of the Test Site or Prototype in accordance with the provisions of these Terms of Use; your failure to comply with these Terms of Use; your infringement, violation, or misappropriation of any third party rights, including copyrights; or any violation of applicable laws or regulations.</li>
    <br><li><b>Partial Nullity</b><br>
    If any court of law, having the jurisdiction to decide on this matter, rules that any provision of these Terms & Conditions is invalid, then that provision will be removed from the Terms & Conditions without affecting the rest of the Terms & Conditions, which shall continue in full force and effect.</li>
    <br><li><b>Changes to the Terms of Use</b><br>
    Costa Rica Reps&trade; reserves the right to modify, suspend, discontinue, disable your access to or otherwise make changes to any part of the Website and/or the Services at any time, without notice, and without liability to you or any third party of any kind. If Costa Rica Reps&trade; changes these Terms of Use, it is your responsibility to review them when using the Website and/or the Services to ensure you are aware of the latest Terms of Use. By using the Website and/or the Services following any modified Terms of Use by Costa Rica Reps&trade;, you agree to be bound by those changes. Any disputes arising under these Terms of Use shall be governed by the Terms of Use in effect at the time the claim or dispute arose. Any changes apply prospectively only to new transactions or activities after the date of the change.</li>
    <br><li><b>Termination</b><br>
    Costa Rica Reps&trade; may, at its sole discretion, terminate these Terms of Use for any reason and at any time without notice, and without liability to you of any kind whatsoever. Following termination, all of the legal rights, obligations and liabilities that you and Costa Rica Reps&trade;  have benefited from, been subject to (or which have accrued during the time these Terms of Use have been in force) or which are expressed to continue indefinitely, shall be unaffected.</li>
</ol>