<h3 style="margin-top: 0px">II.PAYMENT POLICIES</h3>
<h3>1. Payment Conditions</h3>
<ol class="tcList3">
    <li>Costa Rica Reps works based on prepayment and our prices reflect this. Through the years we have established strategical alliances with our providers and privileges when asigning blockings and priority for waiting Lists and Reservations. This based on our credibility and prepayment policy, which has also allowed us to negotiate special net rates. Mantaining our prepayment policy has provided us with a clear advantage from the reservations and operations stand point and results in our bookings being favoured as our providers value the fact that prepayments allow them to work finacially stable, avoid extra cost in credits and ultimately ensure a quality service is provided which is our paramount goal.</li>
    <li><b>Individual (FIT's) Bookings:</b> Costa Rica Reps considers an F.I.T any party between 1 to 9 travellers (1-4 rooms). For such bookings, an invoice will be sent at the time a booking is confirmed and final payment is due to be credited in our account 30 days prior to arrival date. In the event of a reservation received within 30 days prior to arrival date, full payment should be sent as soon as Costa Rica Reps confirms the booking request. Certain hotels may require additional extemporary deposits to guarantee space, especially during the high season. We will be advising you on an individual case basis where such guarantee deposits are required in order to secure the space and secure your reservations.</li>
    <li><b>Group Bookings:</b> Costa Rica Reps considers a group any party with 10 or more travellers (05 or more rooms). The groups will be confirmed in writing based on the requests made and a proforna invoice will be sent stating the deposit and final payment deadlines. A deposit of the 50% over the total amount invoiced is required 60 days before the group arrival. The balance should be sent 30 days prior to arrival date. In the event of a reservation received within 45 days prior to arrival date, full payment should be sent as soon as Costa Rica Reps confirms the booking request.</li>
    <li><b>Important notes:</b>
        <ul>
            <li>Hotels may require additional deposits to guarantee space, especially during the high season or when there are specific numbers of rooms involved. Costa Rica Reps will notify the booking agent should an additional deposit be required.</li>
            <li>Hotels can only guarantee reservations upon received of full payment and some hotels may cancel any reservations and sell the rooms to another client if they do not have a payment on the specified due date. It is important for us to receive your payment as soon as possible so we can process the respective guarantee payments to hotels and service providers in time and this way we will ensure all reservations will be honoured.</li>
            <li>If this final installment is not received when due, Costa Rica Reps reserves the right to treat the reservation as canceled.</li>
        </ul></li>
</ol>