<h3 style="margin-top: 0px">III.CANCELLATION POLICIES</h3>
<h3>1. Cancellations made by you</h3>
<ol class="tcList3">
    <li>We understand how frustrating it is for a traveller to have to cancel their trip due to conditions of force majeur, in particular in those cases where the trip was planned well in advance. Costa Rica Reps also plans these trips accordingly, uses resources and time to reserve a variety of services including lecturers, guides, drivers, extra office staff, tours, transportation and accommodation and we also need to abide to the cancellation and refund policies established by our suppliers. Therefore we adhere to the Cancellation policies outlined below.</li>
    <li>With this in mind, we strongly recommend that all our mutual guests travellers are advised to purchase a fully comprehensive travel insurance. Please refer to the insurance section for details.</li>
    <li>A last minute cancellation of a service is a cancellation where a client is unable or decides not to use or participate in a service at their discretion, due to any unforeseen situation or for not having verifying details with Costa Rica Reps in advance to their full satisfaction prior to confirming their booking, and a formal cancellation is received by telephone, fax, e-mail, letter or personal announcement, through a guide or service representative which is made of our knowledge within a time frame where a service cannot be cancelled. See our section &quot;Cancellations of Package Tour Arrangements&quot;</li>
    <li>A no-show is the case where a client is unable or decides not to use or participate in a service at his own discretion or due to any unforeseen situation, or for not having verifying details with Costa Rica Reps in advance to their full satisfaction and does not notify us accordingly to cancel the service.</li>
    <li>Cancellation fees apply even if a person transfers to another tour or different start date.</li>
    <li>Deposits required to guarantee hotel space or guides may be non-refundable.</li>
</ol>